[build]
  command = "npm run build && npm run export"
  publish = "out"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://your-go-backend-url.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200